baseURL = 'https://cjreilly.tech'
languageCode = 'en-us'
theme='cozy'
[services]
  [services.googleAnalytics]
    id = "G-XXXXXXXXXX"

[params]
    customCss = ["css/custom.css"]

[menu]
[[menu.nav]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.nav]]
  name = "Blog"
  url = "/post/"
  weight = 2
[[menu.nav]]
  name = "About"
  url = "/about/"
  weight = 3
